version: '3'

services:

  web:
    build: ./infra/local/php
    volumes:
      - .:/var/www
      - ./infra/local/php/php.ini:/usr/local/etc/php/php.ini
    depends_on:
      - postgres

  nginx:
    build: ./infra/local/nginx
    ports:
      - "8888:80"
    volumes:
      - .:/var/www
      - ./infra/local/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - web
    # restart: always

  postgres:
    image: postgres:14
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      PGPASSWORD: postgres
      POSTGRES_DB: main
      TZ: "Asia/Tokyo"
    ports:
      - 5432:5432
    volumes:
      - ./infra/local/postgres/data:/var/lib/postgresql/data
      - ./infra/local/postgres/logs:/var/log
